services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apartment_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - ./mysql-db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"


  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
